### ISSUE TITLE
List of M302 identifiers

### ISSUE THREAD

**Issue by lasthopegf** [Cm0nsters/MiPy-Classic#1]
This seems to be the complete list of supported command identifiers.

#define DL_NO_CARD            0x01 //No card
#define DL_CARD_QUER          0x02 //Xun card
#define DL_CARD_ANTICOLLISION 0x03 //Card anti-collision (anti-collision mechanism Anticollision Loop)
#define DL_CARD_SELECT        0x04 //Select card
#define DL_CARD_AUTH_KEY      0x05 //Verify card password (Authentication)
#define DL_CARD_READ_DATA     0x06 ///Read card data
#define DL_CARD_WRITE_DATA    0x07 //Write card data
#define DL_CARD_WRITE_BLOCK   0x08 //Card block value operation (subtraction/addition)
#define DL_CARD_HALT          0x09 //terminate card operation
#define DL_CARD_QUERY_EX      0x0A //Enhanced card search (including : Card anti-collision, select card)
#define DL_DOWN_KEY           0x0B //password download
#define DL_CRC_ERR            0x0C //Check error
#define DL_UNKNOW_COMMAND     0x0D //Undefined command
#define DL_READ_CARD_ERR      0x0E //Card reading error
#define DL_WRITE_CARD_ERR     0x0F //Write card error
#define DL_PASSWORD_ERR       0x10 //wrong password
#define DL_UNKNOW             0x11 //unknown mistake
#define DL_FIND               0x12 //Check if the device exists
#define DL_BEEP               0x13 //Beep

Supposedly originating from the author who developed this in the scope of a diploma thesis...
You can google for this to find some more details in chinese documents...

**Comment by Cm0nsters** [comment]
This is super useful! I'll have to look up some of these documents more online. Thank you for bringing this to light!
